# Generated by Django 4.2.5 on 2023-09-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('interest', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('learningstyle', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
