# Generated by Django 4.2.5 on 2023-09-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_ouruser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ouruser',
            old_name='name',
            new_name='username',
        ),
    ]
