# Generated by Django 4.2.5 on 2023-09-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_username_ouruser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ouruser',
            name='name',
        ),
    ]
